name: push_notification_service
description: Huawei push service
environment:
  sdk: ">=3.13.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  huawei_push:
    git:
      url: https://github.com/crasowas/hms-flutter-plugin.git
      path: flutter-hms-push
  push_notification_interface:
    path: ../../interface/push_notification_interface

dev_dependencies:
  carapacik_lints: ^3.13.1
