targets:
  $default:
    sources:
      - $package$
      - lib/**
      - pubspec.yaml
      - test/**
    builders:
      freezed:
        generate_for:
          - '**/bloc/**'
        options:
          copy_with: false
