
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Ensure all files are commited
    # ensure_git_status_clean

    # increment_build_number(xcodeproj: "Runner.xcodeproj")

    build_app(workspace: "Runner.xcworkspace", scheme: "staging")

    upload_to_testflight
  end
end
