import 'package:bag24/src/core/constant/localization/generated/l10n.dart';
import 'package:bag24/src/core/utils/extensions/extensions.dart';
import 'package:collection/collection.dart';
import 'package:dio/dio.dart';
import 'package:flutter/widgets.dart';
import 'package:rest_client/result_response.dart';

// <error name>$<service prefix>(<error code>)
enum NetworkExceptionType(final int? code) {
  $unknown(null),
  validation(2000),
  internal(5000),

  // accounts
  cantSendOtpTooOften$a(10001),
  userNotFound$a(10002),
  invalidOtpCode$a(10003),
  otpCodeIsExpired$a(10004),
  moaIsAlreadyIntegrated$a(10005),
  userIsAlreadyRegistered$a(10006),
  allAgreementsMustBeAccepted$a(10007),
  sessionIsAlreadyExpired$a(10008),
  userIsNotIntegratedWithMoa$a(10009),
  userNotRegisteredInMoa$a(10010),

  // payments
  paymentNotFound$p(11000),
  bindingNotFound$p(11001),
  invalidPaymentStatus$p(11002),
  userNotFound$p(11003),
  userNotFoundInMoa$p(11004),
  terminalNotFound$p(11005),
  sumMisMatch$p(11006),
  impossibleSendOtpCode$p(11007),
  invalidMoaMilesAmount$p(11008),
  invalidMoaOtpCode$p(11009),
  paymentMethodNotFound$p(11010),
  invalidPaymentMethod$p(11011),

  // storage
  invalidOrderStatus$s(12001),
  orderNotFound$s(12002),
  invalidAmount$s(12003),
  orderLuggageNotFound$s(12004),
  storageNotFound$s(12005),
  defaultRateAlreadyExists$s(12006),
  rateNotFound$s(12007),
  locationNotFound$s(12008),
  fileNotFound$s(12009),
  storageNotDeleted$s(12014),
  rateNotDeleted$s(12015),
  invalidRates$s(12016),
  invalidLuggage$s(12017),
  operationNotFound$s(12018),
  shortApikey$s(12019),
  apikeyUppercaseRequired$s(12020),
  apikeySpecialSymbolRequired$s(12021),
  apikeyNumberRequired$s(12022),
  invalidSpecialOffers$s(12023),
  specialOfferNotFound$s(12024),
  invalidLuggageStatus$s(12025),

  // file storage
  bucketNotFound$fs(13001),
  invalidFileExtension$fs(13003),
  fileNotFound$fs(13004),
  alreadyLocked$fs(13005),
  alreadyUnlocked$fs(13006),
  fileIsNotImage$fs(13007),

  // orders
  storageNotFound$o(14000),
  invalidRates$o(14001),
  photosNotFound$o(14002),
  photosAlreadyLocked$o(14003),
  orderNotFound$o(14004),
  invalidOrderStatus$o(14005),
  luggageNotFound$o(14006),
  paymentNotFound$o(14007),
  invalidAmount$o(14008),
  invalidLuggageStatus$o(14009),
  doNotNeedToPay$o(14010),
  luggageIdsMustBeProvided$o(14011),
  operationNotFound$o(14012),
  invalidPaymentStatus$o(14013),
  invalidPaymentType$o(14014),
  invalidOperationStatus$o(14015),
  depositedDaysNotFound$o(14016),
  sumMisMatch$o(14017),
  userNotFound$o(14018),
  userNotFoundInMoa$o(14019),
  invalidMoaMilesAmount$o(14020),
  impossibleSendOtpCode$o(14021),
  invalidOtpCode$o(14022),
  invalidPayment$o(14023),
  invalidAutoPayment$o(14024),
  rateNotFound$o(14025),
  invalidLuggageData$o(14026),
  invalidSpecialOffers$o(14027),
  paymentFailed$o(14028),
  paymentNotAll$o(14029),
  autoChargeOnFirstPayment$o(14030),
  cantEnableAutoCharge$o(14031),
  incompletePayment$o(14032),
  bindingNotFound$o(14050),

  // trip box
  locationNotFound$tb(15000),
  companyNotFound$tb(15001),
  tripNotFound$tb(15002),
  cityNotFound$tb(15003),
  countryNotFound$tb(15004),
  cityAlreadyExists$tb(15005),
  countryAlreadyExists$tb(15006),
  locationAlreadyExists$tb(15007),
  invalidCityData$tb(15008),
  invalidCountryData$tb(15009),
  countryCantDeleted$tb(15010),
  locationCantDeleted$tb(15011),
  cityCantDeleted$tb(15012),
  locationTagNotFound$tb(15013),

  // gate
  jwtDecodeError$g(16000),
  jwtExpireError$g(16001),
  accessTokenRequired$g(16002),
  refreshTokenRequired$g(16003),
  invalidUserStatus$g(16004),
  agreementsMustBeAccepted$g(16007);

  static NetworkExceptionType? byStatusCode(DioException exception) {
    if (exception.response?.statusCode == 422) {
      return NetworkExceptionType.validation;
    }
    try {
      final result = ResultResponse<void>.fromJson(exception.response?.data as Map<String, dynamic>);
      return NetworkExceptionType.values.firstWhereOrNull((e) => e.code == result.errorCode);
    } on Object catch (_) {
      return null;
    }
  }

  String localizedText(BuildContext context) {
    final AppLocalizations l10n = context.l10n;
    return switch (this) {
      NetworkExceptionType.$unknown => l10n.unknownServerException,
      NetworkExceptionType.validation => l10n.validationRequestError,
      NetworkExceptionType.internal => l10n.internalServerError,
      NetworkExceptionType.cantSendOtpTooOften$a => l10n.cantSendOtpTooOften,
      NetworkExceptionType.userNotFound$a => l10n.userNotFound,
      NetworkExceptionType.invalidOtpCode$a => l10n.invalidOtpCode,
      NetworkExceptionType.otpCodeIsExpired$a => l10n.otpCodeIsExpired,
      NetworkExceptionType.moaIsAlreadyIntegrated$a => l10n.moaIsAlreadyIntegrated,
      NetworkExceptionType.userIsAlreadyRegistered$a => l10n.userIsAlreadyRegistered,
      NetworkExceptionType.allAgreementsMustBeAccepted$a => l10n.allAgreementsMustBeAccepted,
      NetworkExceptionType.sessionIsAlreadyExpired$a => l10n.sessionIsAlreadyExpired,
      NetworkExceptionType.userIsNotIntegratedWithMoa$a => l10n.userIsNotIntegratedWithMoa,
      NetworkExceptionType.userNotRegisteredInMoa$a => l10n.userNotRegisteredInMoa,
      NetworkExceptionType.paymentNotFound$p => l10n.paymentNotFound,
      NetworkExceptionType.bindingNotFound$p => l10n.bindingNotFound,
      NetworkExceptionType.invalidPaymentStatus$p => l10n.invalidPaymentStatus,
      NetworkExceptionType.userNotFound$p => l10n.userNotFound,
      NetworkExceptionType.userNotFoundInMoa$p => l10n.userNotFoundInMoa,
      NetworkExceptionType.terminalNotFound$p => l10n.terminalNotFound,
      NetworkExceptionType.sumMisMatch$p => l10n.sumMisMatch,
      NetworkExceptionType.impossibleSendOtpCode$p => l10n.impossibleSendOtpCode,
      NetworkExceptionType.invalidMoaMilesAmount$p => l10n.invalidMoaMilesAmount,
      NetworkExceptionType.invalidMoaOtpCode$p => l10n.invalidMoaOtpCode,
      NetworkExceptionType.paymentMethodNotFound$p => l10n.paymentMethodNotFound,
      NetworkExceptionType.invalidPaymentMethod$p => l10n.invalidPaymentMethod,
      NetworkExceptionType.invalidOrderStatus$s => l10n.invalidOrderStatus,
      NetworkExceptionType.orderNotFound$s => l10n.orderNotFound,
      NetworkExceptionType.invalidAmount$s => l10n.invalidAmount,
      NetworkExceptionType.orderLuggageNotFound$s => l10n.orderLuggageNotFound,
      NetworkExceptionType.storageNotFound$s => l10n.storageNotFound,
      NetworkExceptionType.defaultRateAlreadyExists$s => l10n.defaultRateAlreadyExists,
      NetworkExceptionType.rateNotFound$s => l10n.rateNotFound,
      NetworkExceptionType.locationNotFound$s => l10n.locationNotFound,
      NetworkExceptionType.fileNotFound$s => l10n.fileNotFound,
      NetworkExceptionType.storageNotDeleted$s => l10n.storageNotDeleted,
      NetworkExceptionType.rateNotDeleted$s => l10n.rateNotDeleted,
      NetworkExceptionType.invalidRates$s => l10n.invalidRates,
      NetworkExceptionType.invalidLuggage$s => l10n.invalidLuggage,
      NetworkExceptionType.operationNotFound$s => l10n.operationNotFound,
      NetworkExceptionType.shortApikey$s => l10n.shortApikey,
      NetworkExceptionType.apikeyUppercaseRequired$s => l10n.apikeyUppercaseRequired,
      NetworkExceptionType.apikeySpecialSymbolRequired$s => l10n.apikeySpecialSymbolRequired,
      NetworkExceptionType.apikeyNumberRequired$s => l10n.apikeyNumberRequired,
      NetworkExceptionType.invalidSpecialOffers$s => l10n.invalidSpecialOffers,
      NetworkExceptionType.specialOfferNotFound$s => l10n.specialOfferNotFound,
      NetworkExceptionType.invalidLuggageStatus$s => l10n.invalidLuggageStatus,
      NetworkExceptionType.bucketNotFound$fs => l10n.bucketNotFound,
      NetworkExceptionType.invalidFileExtension$fs => l10n.invalidFileExtension,
      NetworkExceptionType.fileNotFound$fs => l10n.fileNotFound,
      NetworkExceptionType.alreadyLocked$fs => l10n.alreadyLocked,
      NetworkExceptionType.alreadyUnlocked$fs => l10n.alreadyUnlocked,
      NetworkExceptionType.fileIsNotImage$fs => l10n.fileIsNotImage,
      NetworkExceptionType.storageNotFound$o => l10n.storageNotFound,
      NetworkExceptionType.invalidRates$o => l10n.invalidRates,
      NetworkExceptionType.photosNotFound$o => l10n.photosNotFound,
      NetworkExceptionType.photosAlreadyLocked$o => l10n.photosAlreadyLocked,
      NetworkExceptionType.orderNotFound$o => l10n.orderNotFound,
      NetworkExceptionType.invalidOrderStatus$o => l10n.invalidOrderStatus,
      NetworkExceptionType.luggageNotFound$o => l10n.luggageNotFound,
      NetworkExceptionType.paymentNotFound$o => l10n.paymentNotFound,
      NetworkExceptionType.invalidAmount$o => l10n.invalidAmount,
      NetworkExceptionType.invalidLuggageStatus$o => l10n.invalidLuggageStatus,
      NetworkExceptionType.doNotNeedToPay$o => l10n.doNotNeedToPay,
      NetworkExceptionType.luggageIdsMustBeProvided$o => l10n.luggageIdsMustBeProvided,
      NetworkExceptionType.operationNotFound$o => l10n.operationNotFound,
      NetworkExceptionType.invalidPaymentStatus$o => l10n.invalidPaymentStatus,
      NetworkExceptionType.invalidPaymentType$o => l10n.invalidPaymentType,
      NetworkExceptionType.invalidOperationStatus$o => l10n.invalidOperationStatus,
      NetworkExceptionType.depositedDaysNotFound$o => l10n.depositedDaysNotFound,
      NetworkExceptionType.sumMisMatch$o => l10n.sumMisMatch,
      NetworkExceptionType.userNotFound$o => l10n.userNotFound,
      NetworkExceptionType.userNotFoundInMoa$o => l10n.userNotFoundInMoa,
      NetworkExceptionType.invalidMoaMilesAmount$o => l10n.invalidMoaMilesAmount,
      NetworkExceptionType.impossibleSendOtpCode$o => l10n.impossibleSendOtpCode,
      NetworkExceptionType.invalidOtpCode$o => l10n.invalidOtpCode,
      NetworkExceptionType.invalidPayment$o => l10n.invalidPayment,
      NetworkExceptionType.invalidAutoPayment$o => l10n.invalidAutoPayment,
      NetworkExceptionType.rateNotFound$o => l10n.rateNotFound,
      NetworkExceptionType.invalidLuggageData$o => l10n.invalidLuggageData,
      NetworkExceptionType.invalidSpecialOffers$o => l10n.invalidSpecialOffers,
      NetworkExceptionType.paymentFailed$o => l10n.paymentFailed,
      NetworkExceptionType.paymentNotAll$o => l10n.paymentNotAll,
      NetworkExceptionType.autoChargeOnFirstPayment$o => l10n.autoChargeOnFirstPayment,
      NetworkExceptionType.cantEnableAutoCharge$o => l10n.cantEnableAutoCharge,
      NetworkExceptionType.incompletePayment$o => l10n.incompletePayment,
      NetworkExceptionType.bindingNotFound$o => l10n.bindingNotFound,
      NetworkExceptionType.locationNotFound$tb => l10n.airportNotFound,
      NetworkExceptionType.companyNotFound$tb => l10n.companyNotFound,
      NetworkExceptionType.tripNotFound$tb => l10n.tripNotFound,
      NetworkExceptionType.cityNotFound$tb => l10n.cityNotFound,
      NetworkExceptionType.countryNotFound$tb => l10n.countryNotFound,
      NetworkExceptionType.cityAlreadyExists$tb => l10n.cityAlreadyExists,
      NetworkExceptionType.countryAlreadyExists$tb => l10n.countryAlreadyExists,
      NetworkExceptionType.locationAlreadyExists$tb => l10n.airportAlreadyExists,
      NetworkExceptionType.invalidCityData$tb => l10n.invalidCityData,
      NetworkExceptionType.invalidCountryData$tb => l10n.invalidCountryData,
      NetworkExceptionType.countryCantDeleted$tb => l10n.countryCantDeleted,
      NetworkExceptionType.locationCantDeleted$tb => l10n.airportCantDeleted,
      NetworkExceptionType.cityCantDeleted$tb => l10n.cityCantDeleted,
      NetworkExceptionType.locationTagNotFound$tb => l10n.locationTagNotFound,
      NetworkExceptionType.jwtDecodeError$g => l10n.jwtDecodeError,
      NetworkExceptionType.jwtExpireError$g => l10n.jwtExpireError,
      NetworkExceptionType.accessTokenRequired$g => l10n.accessTokenRequired,
      NetworkExceptionType.refreshTokenRequired$g => l10n.refreshTokenRequired,
      NetworkExceptionType.invalidUserStatus$g => l10n.invalidUserStatus,
      NetworkExceptionType.agreementsMustBeAccepted$g => l10n.allAgreementsMustBeAccepted,
    };
  }
}
