import 'package:flutter/material.dart';

@immutable
class const ColorsX({
  required final Color baseBgPrimary,
  required final Color baseBgPrimaryInverse,
  required final Color baseBgSecondary,
  required final Color borderBrand,
  required final Color borderPrimary,
  required final Color borderSecondary,
  required final Color iconDisabled,
  required final Color iconAccent,
  required final Color iconPrimary,
  required final Color iconPrimaryInverse,
  required final Color iconSecondary,
  required final Color iconTertiary,
  required final Color badgeBgPrimary,
  required final Color badgeBgSecondary,
  required final Color badgeBorder,
  required final Color buttonBgDisabled,
  required final Color buttonBgAlpha,
  required final Color buttonBgSecondary,
  required final Color buttonBgSecondaryInverse,
  required final Color buttonBgTertiary,
  required final Color cellBgPrimary,
  required final Color cellBgSecondary,
  required final Color cellBorderActive,
  required final Color inputBgPrimary,
  required final Color inputBgSecondary,
  required final Color progressBar,
  required final Color trackBar,
  required final Color checkbox,
  required final Color checkboxBg,
  required final Color selectCheckbox,
  required final Color bgSnackBar,
  required final Color bgTooltip,
  required final Color tabBgPrimary,
  required final Color tabBgSecondary,
  required final Color toggleBgDisabled,
  required final Color toggleBgSecondary,
  required final Color toggleHandle,
  required final Color toggleHandleDisabled,
  required final Color togglePrimary,
  required final Color textDisabled,
  required final Color textAccent,
  required final Color textPrimary,
  required final Color textPrimaryInverse,
  required final Color textSecondary,
  required final Color textSecondaryInverse,
  required final Color textTertiary,
  required final Color error,
  required final Color errorLight,
  required final Color info,
  required final Color infoLight,
  required final Color success,
  required final Color successLight,
  required final Color warning,
  required final Color warningLight,
  required final Color flybag,
  required final Color lostFound,
  required final Color mileOnAir,
  required final Color mileOnAirLight,
}) extends ThemeExtension<ColorsX> {
  @override
  ColorsX copyWith({
    Color? baseBgPrimary,
    Color? baseBgPrimaryInverse,
    Color? baseBgSecondary,
    Color? borderBrand,
    Color? borderPrimary,
    Color? borderSecondary,
    Color? iconDisabled,
    Color? iconAccent,
    Color? iconPrimary,
    Color? iconPrimaryInverse,
    Color? iconSecondary,
    Color? iconTertiary,
    Color? badgeBgPrimary,
    Color? badgeBgSecondary,
    Color? badgeBorder,
    Color? buttonBgDisabled,
    Color? buttonBgAlpha,
    Color? buttonBgSecondary,
    Color? buttonBgSecondaryInverse,
    Color? buttonBgTertiary,
    Color? cellBgPrimary,
    Color? cellBgSecondary,
    Color? cellBorderActive,
    Color? inputBgPrimary,
    Color? inputBgSecondary,
    Color? progressBar,
    Color? trackBar,
    Color? checkbox,
    Color? checkboxBg,
    Color? selectCheckbox,
    Color? bgSnackBar,
    Color? bgTooltip,
    Color? tabBgPrimary,
    Color? tabBgSecondary,
    Color? toggleBgDisabled,
    Color? toggleBgSecondary,
    Color? toggleHandle,
    Color? toggleHandleDisabled,
    Color? togglePrimary,
    Color? textDisabled,
    Color? textAccent,
    Color? textPrimary,
    Color? textPrimaryInverse,
    Color? textSecondary,
    Color? textSecondaryInverse,
    Color? textTertiary,
    Color? error,
    Color? errorLight,
    Color? info,
    Color? infoLight,
    Color? success,
    Color? successLight,
    Color? warning,
    Color? warningLight,
    Color? flybag,
    Color? lostFound,
    Color? mileOnAir,
    Color? mileOnAirLight,
  }) => ColorsX(
    baseBgPrimary: baseBgPrimary ?? this.baseBgPrimary,
    baseBgPrimaryInverse: baseBgPrimaryInverse ?? this.baseBgPrimaryInverse,
    baseBgSecondary: baseBgSecondary ?? this.baseBgSecondary,
    borderBrand: borderBrand ?? this.borderBrand,
    borderPrimary: borderPrimary ?? this.borderPrimary,
    borderSecondary: borderSecondary ?? this.borderSecondary,
    iconDisabled: iconDisabled ?? this.iconDisabled,
    iconAccent: iconAccent ?? this.iconAccent,
    iconPrimary: iconPrimary ?? this.iconPrimary,
    iconPrimaryInverse: iconPrimaryInverse ?? this.iconPrimaryInverse,
    iconSecondary: iconSecondary ?? this.iconSecondary,
    iconTertiary: iconTertiary ?? this.iconTertiary,
    badgeBgPrimary: badgeBgPrimary ?? this.badgeBgPrimary,
    badgeBgSecondary: badgeBgSecondary ?? this.badgeBgSecondary,
    badgeBorder: badgeBorder ?? this.badgeBorder,
    buttonBgDisabled: buttonBgDisabled ?? this.buttonBgDisabled,
    buttonBgAlpha: buttonBgAlpha ?? this.buttonBgAlpha,
    buttonBgSecondary: buttonBgSecondary ?? this.buttonBgSecondary,
    buttonBgSecondaryInverse: buttonBgSecondaryInverse ?? this.buttonBgSecondaryInverse,
    buttonBgTertiary: buttonBgTertiary ?? this.buttonBgTertiary,
    cellBgPrimary: cellBgPrimary ?? this.cellBgPrimary,
    cellBgSecondary: cellBgSecondary ?? this.cellBgSecondary,
    cellBorderActive: cellBorderActive ?? this.cellBorderActive,
    inputBgPrimary: inputBgPrimary ?? this.inputBgPrimary,
    inputBgSecondary: inputBgSecondary ?? this.inputBgSecondary,
    progressBar: progressBar ?? this.progressBar,
    trackBar: trackBar ?? this.trackBar,
    checkbox: checkbox ?? this.checkbox,
    checkboxBg: checkboxBg ?? this.checkboxBg,
    selectCheckbox: selectCheckbox ?? this.selectCheckbox,
    bgSnackBar: bgSnackBar ?? this.bgSnackBar,
    bgTooltip: bgTooltip ?? this.bgTooltip,
    tabBgPrimary: tabBgPrimary ?? this.tabBgPrimary,
    tabBgSecondary: tabBgSecondary ?? this.tabBgSecondary,
    toggleBgDisabled: toggleBgDisabled ?? this.toggleBgDisabled,
    toggleBgSecondary: toggleBgSecondary ?? this.toggleBgSecondary,
    toggleHandle: toggleHandle ?? this.toggleHandle,
    toggleHandleDisabled: toggleHandleDisabled ?? this.toggleHandleDisabled,
    togglePrimary: togglePrimary ?? this.togglePrimary,
    textDisabled: textDisabled ?? this.textDisabled,
    textAccent: textAccent ?? this.textAccent,
    textPrimary: textPrimary ?? this.textPrimary,
    textPrimaryInverse: textPrimaryInverse ?? this.textPrimaryInverse,
    textSecondary: textSecondary ?? this.textSecondary,
    textSecondaryInverse: textSecondaryInverse ?? this.textSecondaryInverse,
    textTertiary: textTertiary ?? this.textTertiary,
    error: error ?? this.error,
    errorLight: errorLight ?? this.errorLight,
    info: info ?? this.info,
    infoLight: infoLight ?? this.infoLight,
    success: success ?? this.success,
    successLight: successLight ?? this.successLight,
    warning: warning ?? this.warning,
    warningLight: warningLight ?? this.warningLight,
    flybag: flybag ?? this.flybag,
    lostFound: lostFound ?? this.lostFound,
    mileOnAir: mileOnAir ?? this.mileOnAir,
    mileOnAirLight: mileOnAirLight ?? this.mileOnAirLight,
  );

  @override
  ColorsX lerp(ColorsX? other, double t) {
    if (other is! ColorsX) {
      return this;
    }
    return ColorsX(
      baseBgPrimary: Color.lerp(baseBgPrimary, other.baseBgPrimary, t)!,
      baseBgPrimaryInverse: Color.lerp(baseBgPrimaryInverse, other.baseBgPrimaryInverse, t)!,
      baseBgSecondary: Color.lerp(baseBgSecondary, other.baseBgSecondary, t)!,
      borderBrand: Color.lerp(borderBrand, other.borderBrand, t)!,
      borderPrimary: Color.lerp(borderPrimary, other.borderPrimary, t)!,
      borderSecondary: Color.lerp(borderSecondary, other.borderSecondary, t)!,
      iconDisabled: Color.lerp(iconDisabled, other.iconDisabled, t)!,
      iconAccent: Color.lerp(iconAccent, other.iconAccent, t)!,
      iconPrimary: Color.lerp(iconPrimary, other.iconPrimary, t)!,
      iconPrimaryInverse: Color.lerp(iconPrimaryInverse, other.iconPrimaryInverse, t)!,
      iconSecondary: Color.lerp(iconSecondary, other.iconSecondary, t)!,
      iconTertiary: Color.lerp(iconTertiary, other.iconTertiary, t)!,
      badgeBgPrimary: Color.lerp(badgeBgPrimary, other.badgeBgPrimary, t)!,
      badgeBgSecondary: Color.lerp(badgeBgSecondary, other.badgeBgSecondary, t)!,
      badgeBorder: Color.lerp(badgeBorder, other.badgeBorder, t)!,
      buttonBgDisabled: Color.lerp(buttonBgDisabled, other.buttonBgDisabled, t)!,
      buttonBgAlpha: Color.lerp(buttonBgAlpha, other.buttonBgAlpha, t)!,
      buttonBgSecondary: Color.lerp(buttonBgSecondary, other.buttonBgSecondary, t)!,
      buttonBgSecondaryInverse: Color.lerp(buttonBgSecondaryInverse, other.buttonBgSecondaryInverse, t)!,
      buttonBgTertiary: Color.lerp(buttonBgTertiary, other.buttonBgTertiary, t)!,
      cellBgPrimary: Color.lerp(cellBgPrimary, other.cellBgPrimary, t)!,
      cellBgSecondary: Color.lerp(cellBgSecondary, other.cellBgSecondary, t)!,
      cellBorderActive: Color.lerp(cellBorderActive, other.cellBorderActive, t)!,
      inputBgPrimary: Color.lerp(inputBgPrimary, other.inputBgPrimary, t)!,
      inputBgSecondary: Color.lerp(inputBgSecondary, other.inputBgSecondary, t)!,
      progressBar: Color.lerp(progressBar, other.progressBar, t)!,
      trackBar: Color.lerp(trackBar, other.trackBar, t)!,
      checkbox: Color.lerp(checkbox, other.checkbox, t)!,
      checkboxBg: Color.lerp(checkboxBg, other.checkboxBg, t)!,
      selectCheckbox: Color.lerp(selectCheckbox, other.selectCheckbox, t)!,
      bgSnackBar: Color.lerp(bgSnackBar, other.bgSnackBar, t)!,
      bgTooltip: Color.lerp(bgTooltip, other.bgTooltip, t)!,
      tabBgPrimary: Color.lerp(tabBgPrimary, other.tabBgPrimary, t)!,
      tabBgSecondary: Color.lerp(tabBgSecondary, other.tabBgSecondary, t)!,
      toggleBgDisabled: Color.lerp(toggleBgDisabled, other.toggleBgDisabled, t)!,
      toggleBgSecondary: Color.lerp(toggleBgSecondary, other.toggleBgSecondary, t)!,
      toggleHandle: Color.lerp(toggleHandle, other.toggleHandle, t)!,
      toggleHandleDisabled: Color.lerp(toggleHandleDisabled, other.toggleHandleDisabled, t)!,
      togglePrimary: Color.lerp(togglePrimary, other.togglePrimary, t)!,
      textDisabled: Color.lerp(textDisabled, other.textDisabled, t)!,
      textAccent: Color.lerp(textAccent, other.textAccent, t)!,
      textPrimary: Color.lerp(textPrimary, other.textPrimary, t)!,
      textPrimaryInverse: Color.lerp(textPrimaryInverse, other.textPrimaryInverse, t)!,
      textSecondary: Color.lerp(textSecondary, other.textSecondary, t)!,
      textSecondaryInverse: Color.lerp(textSecondaryInverse, other.textSecondaryInverse, t)!,
      textTertiary: Color.lerp(textTertiary, other.textTertiary, t)!,
      error: Color.lerp(error, other.error, t)!,
      errorLight: Color.lerp(errorLight, other.errorLight, t)!,
      info: Color.lerp(info, other.info, t)!,
      infoLight: Color.lerp(infoLight, other.infoLight, t)!,
      success: Color.lerp(success, other.success, t)!,
      successLight: Color.lerp(successLight, other.successLight, t)!,
      warning: Color.lerp(warning, other.warning, t)!,
      warningLight: Color.lerp(warningLight, other.warningLight, t)!,
      flybag: Color.lerp(flybag, other.flybag, t)!,
      lostFound: Color.lerp(lostFound, other.lostFound, t)!,
      mileOnAir: Color.lerp(mileOnAir, other.mileOnAir, t)!,
      mileOnAirLight: Color.lerp(mileOnAirLight, other.mileOnAirLight, t)!,
    );
  }
}

@immutable
class const IconsX({
  required final String bag24Logo,
  required final String bag24Icon,
  required final String mileOnAirLogo,
}) extends ThemeExtension<IconsX> {
  @override
  IconsX copyWith({String? bag24Logo, String? bag24Icon, String? mileOnAirLogo}) => IconsX(
    bag24Logo: bag24Logo ?? this.bag24Logo,
    bag24Icon: bag24Icon ?? this.bag24Icon,
    mileOnAirLogo: mileOnAirLogo ?? this.mileOnAirLogo,
  );

  @override
  ThemeExtension<IconsX> lerp(covariant ThemeExtension<IconsX>? other, double t) {
    if (other is! IconsX) {
      return this;
    }

    return IconsX(
      bag24Logo: _lerpString(bag24Logo, other.bag24Logo, t),
      bag24Icon: _lerpString(bag24Icon, other.bag24Icon, t),
      mileOnAirLogo: _lerpString(mileOnAirLogo, other.mileOnAirLogo, t),
    );
  }

  String _lerpString(String a, String b, double t) => b;
}
